version: '3.0'
services:
  web-app:
    build: ./web-app
    volumes:
      - ./web-app:/web-app:cached
      - gems:/gems
      - node_modules:/web-app/node_modules
      - packs:/web-app/public/packs
      - rails_cache:/web-app/tmp/cache
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    # environment:
    #   RAILS_ROOT: web-app
  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      # - 80:80
      - 80:8080
      - 443:1443
    depends_on:
      - web-app
    volumes:
      # - ./nginx/conf.d:/etc/nginx/conf.d/
      # - ./nginx/conf.d/web-app.conf:/etc/nginx/conf.d/web-app.conf
      - ./nginx/html:/usr/share/nginx/html
    # environment:
    #   RAILS_ROOT: web-app
      
volumes:
  web-app:
  gems:
  node_modules:
  packs:
  rails_cache: