version: '3.0'
services:
  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    # command: bash -c "nginx"
    # depends_on:
    #   - web-app
    ports:
      - 8080:8080
      - 80:80
    volumes:
      # - ./nginx/conf.d:/etc/nginx/conf.d/
      # - ./nginx/conf.d/webapp-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d/webapp-nginx.conf:/etc/nginx/conf.d/webapp-nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      